spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prueba_viamatica
    username: postgres
    password: 123
  jpa:
  properties.hibernate:
    jdbc.lob.non_contextual_creation: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: create-drop

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
